RtnApp/config/routes.rb
RtnApp::Application.routes.draw do

  match 'portal/rtn' => 'portal#rtn', :via => :get
  match 'portal/ngram' => 'portal#ngram', :via => :get
  match 'portal/execute' => 'portal#execute', :via => :post
  match 'portal/executengram' => 'portal#executengram', :via => :post
  match 'portal/executelanguagegen' => 'portal#executelanguagegen', :via => :post
  match 'portal/executener' => 'portal#executener', :via => :post
  match 'portal/home' => 'portal#home', :via => :get

  root :to => "portal#index" 
end

RtnApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

RtnApp/app/controllers/portal_controller.rb
class PortalController < ApplicationController
  def index
  end
  
  def home
  end
  
  def executener
    load "#{Dir.pwd}/ner/nerc.rb"
    load "#{Dir.pwd}/ner/rule.rb"
    load "#{Dir.pwd}/ner/instance.rb"
    
    seeds = params[:nerSeeds]
    training = params[:nerTraining]
    test = params[:nerTest]
    
    if seeds == nil || training == nil || test == nil
      render :text => "Please input all variables"
      return
    end
    
    seedT = Rule.factory seeds
    nerT = Instance.factory training
    testT = Instance.factory test
    
    ner = Ner.new seedT, nerT, testT
    
    render :text => ner.execute
  end
  
  def executelanguagegen
    load "#{Dir.pwd}/ngram/sentence.rb"
    load "#{Dir.pwd}/ngram/ngram.rb"
    
    training = params[:training]
    seeds = params[:seeds]
    
    if seeds == nil || training == nil
      render :text => "Please input all the variables"
      return
    end
    
    trainingSentences = Sentence.factory training
    ngram = Ngram.new trainingSentences
    
    returnSentence = ""
    results = ngram.languagegen seeds
    
    puts results
    results.each do |result|
      returnSentence = returnSentence + result + "\n"
    end
    
    render :text => returnSentence
  end
  
  def executengram
    load "#{Dir.pwd}/ngram/sentence.rb"
    load "#{Dir.pwd}/ngram/ngram.rb"
    
    sentence = params[:sentence]
    training = params[:training]
    
    if sentence == nil || training == nil
      render :text => "Please input all the variables"
      return
    end
    
    trainingSentences = Sentence.factory training
    ngram = Ngram.new trainingSentences 
    
    render :text => (ngram.prob sentence)
  end
  
  def execute
    load "#{Dir.pwd}/rtncode/rtnm.rb"
    load "#{Dir.pwd}/rtncode/dm.rb"
    load "#{Dir.pwd}/rtncode/sm.rb"
    load "#{Dir.pwd}/rtncode/lib.rb"
    load "#{Dir.pwd}/rtncode/rule.rb"
    load "#{Dir.pwd}/rtncode/rule_tuple.rb"
    
    sentence = params[:sentence]
    dictTxt = params[:dict]
    rtnmTxt = params[:rtnm]
    
    if sentence == nil || sentence.length == 0 || dictTxt == nil || dictTxt.length == 0 || rtnmTxt == nil || rtnmTxt.length == 0
      render :text => "Please input all the variables"
      return
    end
    
    rtnm = Rtnm.flogic rtnmTxt
    dict = Dm.sfactory dictTxt
    
    Lib.setRuleTypes dict, rtnm
    
    returnSentence = "PROCESSING SENTENCE: #{sentence}\r\r"
    
    result = Lib.vs sentence, dict, rtnm
    sm = Sm.new
    sm.sentence = sentence
    result.each do |tr|
			returnSentence = "#{returnSentence}#{tr.prettyprinttos(sm)}\r\r"
		end
		
		returnSentence = "#{returnSentence}Done! Found #{result.length} parse(s)."
    
    render :text => "#{returnSentence}"
  end
end

RtnApp/app/helpers/application_helper.rb
module ApplicationHelper
end

RtnApp/app/helpers/homes_helper.rb
module HomesHelper
end

RtnApp/app/views/portal/home.html.erb
<h2><%= @stuff %></h2>

RtnApp/app/views/portal/index.html.erb
<%= link_to "RTN", portal_rtn_path %>
<%= link_to "NGRAM", portal_ngram_path %>

RtnApp/app/views/portal/rtn.html.erb
<script>
	$(document).ready(function(){
		$("#go").click(function(event){
			event.preventDefault();
			var sentence = $("#sentenceParse").val();
			var dict = $("#dictionary").val();
			var rtnm = $("#rtnspec").val();
			var dataObj = { "sentence": sentence, "dict": dict, "rtnm": rtnm };
			$.ajax({
				type: "POST",
				url: "<%= portal_execute_path %>",
				data: dataObj,
				success: function(newData){
					$("#results").text(newData);
				},
				error: function(a, b, c){
					alert("There was an error, check server log");
				}
			});
		});
	});
</script>
<%= link_to "Home", root_path %>
<table style="width: 100%">
	<tr>
		<th><h2>RTN</h2></th>
		<td><input type="button" id="go" value="Go!" /></td>
	</tr>
	<tr>
		<th>Sentence</th>
		<td><input style="width: 600px;" type="text" id="sentenceParse" value="fruit flies like trees" /></td>
	</tr>
	<tr>
		<th>Results</th>
		<td><textarea id="results" style="width: 600px; height: 400px;" readonly="readonly"></textarea></td>
	</tr>
	<tr>
		<th>Dictionary</th>
		<td>
			<textarea style="width: 600px; height: 200px;" id="dictionary">
fruit noun
flies noun
flies verb
like verb 
like prep
bananas noun
pears noun
smelly adj
john noun
walks verb
walks noun
dog noun
dog verb
in prep
the art
trees noun
		</textarea></td>
	</tr>
	<tr>
		<th>Rtn Spec</th>
		<td>
			<textarea style="width: 600px; height: 200px;" id="rtnspec">
MACHINE S
INIT S0
FINAL S2
BEGIN
S0 NP S1
S1 VP S2
END

MACHINE NP
INIT NP0
FINAL NP2 NP3
BEGIN
NP0 art NP1
NP0 adj NP1
NP1 noun NP2
NP2 noun NP2
NP0 noun NP2
NP2 PP NP3
END

MACHINE VP
INIT VP0
FINAL VP1 VP2 VP3 VP4
BEGIN
VP0 verb VP1
VP1 PP VP2
VP1 NP VP3
VP3 PP VP4
END

MACHINE PP
INIT PP0
FINAL PP2
BEGIN
PP0 prep PP1
PP1 NP PP2
END
</textarea></td>
	</tr>
</table>